month = "C:\\_C_\\August\\Tools"
pycharm = "C:\\Users\\tomul\\AppData\\Local\\JetBrains\\Toolbox\\apps\\PyCharm-C\\ch-0\\211.7628.24\\bin\\pycharm64.exe"
clion = "C:\\Users\\tomul\\AppData\\Local\\JetBrains\\Toolbox\\apps\\CLion\\ch-0\\213.6777.58\\bin\\clion64.exe"
